#!/usr/bin/env node

import { promises as fs } from "node:fs";
import path from "node:path";
import {
  ensureDir,
  formatNow,
  listFilesRecursive,
  loadManifest,
  pathExists,
  publishTmpDir,
  resolveArgTarget,
  resolveTargets,
  rootDir,
  runShellCommand,
  runtimeSkillDir,
  sameFileContent,
  saveManifest,
  skillDir,
  writeJsonFile,
} from "./lib.mjs";

function shellQuote(value) {
  return `'${String(value).replace(/'/g, `'\\''`)}'`;
}

function isPermissionError(error) {
  if (!(error instanceof Error)) {
    return false;
  }
  const code = "code" in error ? error.code : "";
  const text = `${error.message}`.toLowerCase();
  return code === "EPERM" || code === "EACCES" || text.includes("operation not permitted");
}

function parseOptions(argv) {
  return {
    target: resolveArgTarget(argv),
  };
}

function runGate(command, label) {
  const result = runShellCommand(command, rootDir);
  if (!result.ok) {
    console.error(`[FAIL] gate ${label} failed`);
    if (result.stdout.trim()) {
      console.error(result.stdout.trim());
    }
    if (result.stderr.trim()) {
      console.error(result.stderr.trim());
    }
    process.exit(1);
  }
  console.log(`[PASS] gate ${label}`);
}

async function buildSkillPlan(skillName) {
  const sourceBase = skillDir(skillName);
  const runtimeBase = runtimeSkillDir(skillName);
  const sourceFiles = await listFilesRecursive(sourceBase);
  const actions = [];

  for (const relativeFile of sourceFiles) {
    const sourceFile = path.join(sourceBase, relativeFile);
    const runtimeFile = path.join(runtimeBase, relativeFile);
    if (!(await pathExists(runtimeFile))) {
      actions.push({ type: "add", sourceFile, runtimeFile, relativeFile });
      continue;
    }

    const same = await sameFileContent(sourceFile, runtimeFile);
    if (!same) {
      actions.push({ type: "update", sourceFile, runtimeFile, relativeFile });
    }
  }

  return {
    skillName,
    sourceBase,
    runtimeBase,
    totalSourceFiles: sourceFiles.length,
    actions,
  };
}

async function executePlan(plan) {
  for (const action of plan.actions) {
    await ensureDir(path.dirname(action.runtimeFile));
    await fs.copyFile(action.sourceFile, action.runtimeFile);
    const stat = await fs.stat(action.sourceFile);
    await fs.chmod(action.runtimeFile, stat.mode);
  }
}

async function writeManualBundle(plans, outPath) {
  const lines = [
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    "",
    "# Manual publish commands generated by skills:publish",
  ];

  for (const plan of plans) {
    lines.push(`# ${plan.skillName}`);
    for (const action of plan.actions) {
      lines.push(`mkdir -p ${shellQuote(path.dirname(action.runtimeFile))}`);
      lines.push(`cp ${shellQuote(action.sourceFile)} ${shellQuote(action.runtimeFile)}`);
    }
    lines.push("");
  }

  await fs.writeFile(outPath, `${lines.join("\n")}\n`, "utf8");
  await fs.chmod(outPath, 0o755);
}

async function main() {
  const args = process.argv.slice(2);
  const { target } = parseOptions(args);
  const manifest = await loadManifest();
  const targets = resolveTargets(manifest, target);

  // Gate chain
  runGate(
    `bun commands/skills/validate-skills.mjs --profile auto --strict --target ${shellQuote(target)}`,
    "validate",
  );
  runGate(
    `bun commands/skills/deps-skills.mjs --strict --target ${shellQuote(target)}`,
    "deps",
  );
  runGate(`bun commands/skills/smoke-skills.mjs --strict --target ${shellQuote(target)}`, "smoke");
  runGate("bun commands/skills/tidyup-skills.mjs", "tidyup");

  const plans = [];
  for (const skillName of targets) {
    const skillPlan = await buildSkillPlan(skillName);
    plans.push(skillPlan);
  }

  const timestamp = formatNow();
  await ensureDir(publishTmpDir);
  const planPath = path.join(publishTmpDir, `plan-${timestamp}.json`);
  await writeJsonFile(planPath, {
    generatedAt: new Date().toISOString(),
    target,
    plans: plans.map((plan) => ({
      skillName: plan.skillName,
      totalSourceFiles: plan.totalSourceFiles,
      additions: plan.actions.filter((action) => action.type === "add").length,
      updates: plan.actions.filter((action) => action.type === "update").length,
      actions: plan.actions.map((action) => ({
        type: action.type,
        relativeFile: action.relativeFile,
      })),
    })),
  });

  for (const skillName of targets) {
    const entry = manifest.skills.find((skill) => skill.name === skillName);
    if (entry) {
      entry.state = "ReadyToPublish";
    }
  }

  try {
    for (const plan of plans) {
      await executePlan(plan);
    }

    for (const skillName of targets) {
      const entry = manifest.skills.find((skill) => skill.name === skillName);
      if (entry) {
        entry.state = "Published";
      }
    }

    await saveManifest(manifest);

    console.log(`[PASS] skills published to .agents/skills. plan=${planPath}`);
    const verify = runShellCommand(
      `bun commands/skills/verify-runtime-skills.mjs --target ${shellQuote(target)}`,
      rootDir,
    );
    if (!verify.ok) {
      console.error("[FAIL] publish completed but runtime verification failed");
      if (verify.stdout.trim()) {
        console.error(verify.stdout.trim());
      }
      if (verify.stderr.trim()) {
        console.error(verify.stderr.trim());
      }
      process.exit(1);
    }
    if (verify.stdout.trim()) {
      console.log(verify.stdout.trim());
    }
    return;
  } catch (error) {
    if (!isPermissionError(error)) {
      throw error;
    }

    for (const skillName of targets) {
      const entry = manifest.skills.find((skill) => skill.name === skillName);
      if (entry) {
        entry.state = "PendingPublish";
      }
    }
    await saveManifest(manifest);

    const manualPath = path.join(publishTmpDir, `manual-publish-${timestamp}.sh`);
    await writeManualBundle(plans, manualPath);
    console.error("[WARN] runtime path appears protected; publish requires manual commands.");
    console.error(`Generated manual publish bundle: ${manualPath}`);
    console.error(`After running bundle, execute: bun run skills:verify-runtime --target ${target}`);
    process.exit(1);
  }
}

main().catch((error) => {
  console.error("skills:publish failed.");
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
